### ISSUE TITLE
iPhone7 模拟器上实测和系统的没什么区别。。。

### ISSUE THREAD

**Issue by LisonFan** [DreamBuddy/DBCorner#1]
![untitled](https://cloud.githubusercontent.com/assets/9424775/21921244/a5840540-d9a1-11e6-9757-9209618ae1fd.gif)

FPS 工具来源: http://www.jianshu.com/p/66a03c8d126d

**Comment by DreamBuddy** [comment]
@LisonFan 是这样的 1.模拟器本身性能跟真机相差很多 尤其是GPU方面 2.通过CADisplayLink检测FPS是极其不准确的.. 建议使用 系统的Instruments中的Animation进行相关测试~

**Comment by LisonFan** [comment]
@DreamBuddy 确实如此

**Comment by DreamBuddy** [comment]
😁
